### PR TITLE
Ignore *.axd Routes

### PR DESCRIPTION
**Pull request by nikmd23**
This commit is not the most DRY way of fixing the problem, but I noticed that HotTowel simply builds on top of the OOTB templates without changing them, so this is keeping with that strategy.

This commit will allow for *.axd files to be served from HotTowel applications without user changes, which will help to support [Glimpse](http://getGlimpse.com), [ELMAH](http://code.google.com/p/elmah/), [Cassette](http://getcassette.net/) and a host of other open source projects.

### CODE REVIEW

**Comment by johnpapa** [comment]
Just FYI, there is a sister NuGet called HotTowelette. If I merge this then HotTowelette also needs this change. So if you can update both, that'd be great. It is in this repo, in the aptly named folder.

**Comment by nikmd23** [comment]
HotTowelette (`NuGet - Towelette\HotTowelette\App_Start`) doesn't change any routing configuration like HotTowel does. 

Am I missing something?

**Comment by johnpapa** [comment]
Nope, ignore me :)

**Comment by johnpapa** [comment]
Nik - Thinking about adding the suggestions in this link, from Phil Haack. What do you think?

http://haacked.com/archive/2008/07/14/make-routing-ignore-requests-for-a-file-extension.aspx

``` c#
routes.IgnoreRoute("{*allaspx}", new {allaspx=@".*\.aspx(/.*)?"});
routes.IgnoreRoute("{*favicon}", new {favicon=@"(.*/)?favicon.ico(/.*)?"});
```

**Comment by nikmd23** [comment]
I don't think there are very many people running MVC and WebForms together (although there are some) so I don't think this would really hurt.

I'm not sure you need the `favicon.ico` rule since you add a favicon with HotTowel.

My $0.02.

**Pull request merged**
